language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
    - "python setupdb.py && python server.py &"

# command to run tests
script: nosetests

